Basics chapter and nix-shell
rocq-community/fav-ssr pull request #1
Opened 2021-11-09 20:32 UTC by cattingcat

2021-11-09 22:11 UTC, clayrat commented
Thanks! I have a few comments.

2021-11-09 22:14 UTC, clayrat requested changes

2021-11-09 22:14 UTC, clayrat commented on src/basics.v
> +Lemma list_app xs ys zs : (xs ++ ys) ++ zs = xs ++ ys ++ zs.
Let's drop this, it already exists as `catsA`.

2021-11-09 22:14 UTC, clayrat commented on src/basics.v
> +Print app.
Looks like a debugging leftover.

2021-11-09 22:14 UTC, clayrat commented on src/basics.v
> +  if xs is _ :: xs' then (T_app' xs' ys).+1 else 1.
Let's keep this version and drop the previous one.

2021-11-09 22:14 UTC, clayrat commented on src/basics.v
> +Definition iterv {T} := @catrev T.
I think the book calls it `itrev`, not `iterv`. I'd just go with `catrev` here and below without introducing an alias.

2021-11-09 22:15 UTC, clayrat commented on src/basics.v
> +Lemma T_app_complexity xs ys : T_app xs ys = (length xs).+1.
Mathcomp uses `size` instead of `length`.

2021-11-11 23:34 UTC, cattingcat commented
@clayrat Thx for review. I also added first lemma from Selection chapter here

2021-11-12 14:21 UTC, merged